from http.cookies import SimpleCookie
from urllib.parse import urlparse


BILIBILI_COOKIE_KEYS = {
    "SESSDATA",
    "bili_jct",
    "DedeUserID",
    "DedeUserID__ckMd5",
    "sid",
    "buvid3",
    "buvid4",
    "b_nut",
    "b_lsid",
    "bili_ticket",
    "bili_ticket_expires",
}

COOKIE_EXPIRES_AT = "2147483647"
COOKIE_HEADER_PREFIX = "# Netscape HTTP Cookie File\n# Generated by yt-dlp Web.\n\n"
RAW_COOKIE_ATTRIBUTES = {
    "domain",
    "expires",
    "httponly",
    "max-age",
    "path",
    "samesite",
    "secure",
}


def is_bilibili_url(url: str) -> bool:
    hostname = urlparse(url).hostname or ""
    return hostname == "bilibili.com" or hostname.endswith(".bilibili.com")


def has_sessdata(cookie_text: str) -> bool:
    return "SESSDATA" in _cookie_names(cookie_text)


def normalize_bilibili_cookies(cookie_text: str) -> str:
    stripped = cookie_text.strip()
    if not stripped:
        return ""

    if _looks_like_netscape_cookie_file(stripped):
        return _normalize_netscape_cookie_file(stripped)

    return _raw_cookie_header_to_netscape(stripped)


def _cookie_names(cookie_text: str) -> set[str]:
    names = set()
    for line in cookie_text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 7:
            names.add(parts[5])
            continue
        if "=" in line:
            names.add(line.split("=", 1)[0].strip())
    return names


def _looks_like_netscape_cookie_file(cookie_text: str) -> bool:
    for line in cookie_text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if len(line.split("\t")) >= 7:
            return True
    return False


def _normalize_netscape_cookie_file(cookie_text: str) -> str:
    lines = []
    has_cookie = False

    for raw_line in cookie_text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("#"):
            continue

        parts = line.split("\t")
        if len(parts) < 7:
            raise ValueError("Cookie 文件格式不正确，请使用 Netscape cookies.txt 或浏览器 Cookie 字符串")

        domain, include_subdomains, path, https_only, expires_at, name, value = parts[:7]
        if "bilibili.com" not in domain:
            continue

        include_subdomains = "TRUE" if include_subdomains.upper() == "TRUE" else "FALSE"
        https_only = "TRUE" if https_only.upper() == "TRUE" else "FALSE"
        expires_at = expires_at or COOKIE_EXPIRES_AT
        path = path or "/"
        lines.append("\t".join((
            domain,
            include_subdomains,
            path,
            https_only,
            expires_at,
            name,
            value,
        )))
        has_cookie = True

    if not has_cookie:
        raise ValueError("未找到 bilibili.com 的 Cookie")

    return COOKIE_HEADER_PREFIX + "\n".join(lines) + "\n"


def _raw_cookie_header_to_netscape(cookie_text: str) -> str:
    cookie_text = cookie_text.removeprefix("Cookie:").strip()
    parsed = SimpleCookie()

    try:
        parsed.load(cookie_text)
    except Exception as exc:
        raise ValueError("Cookie 字符串格式不正确") from exc

    lines = []
    for name, morsel in parsed.items():
        if not name or name.lower() in RAW_COOKIE_ATTRIBUTES:
            continue
        value = morsel.value
        lines.append("\t".join((
            ".bilibili.com",
            "TRUE",
            "/",
            "FALSE",
            COOKIE_EXPIRES_AT,
            name,
            value,
        )))

    if not lines:
        raise ValueError("未解析到有效 Cookie")

    names = {line.split("\t")[5] for line in lines}
    if not (names & BILIBILI_COOKIE_KEYS):
        raise ValueError("未解析到常见 B 站 Cookie，请确认复制的是 bilibili.com 页面 Cookie")

    return COOKIE_HEADER_PREFIX + "\n".join(lines) + "\n"
